name: Publish Documentation
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
            token: ${{ secrets.GH_PAGES_TOKEN }}
      - name: Install mdBook
        run: |
          mkdir mdbook
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.22/mdbook-v0.4.22-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: Deploy to GitHub Pages
        run: |
          cd docs
          mdbook build
          git worktree add gh-pages
          git config --global user.name "GitHub Actions"
          git config --global user.email ""
          cd gh-pages
          git update-ref -d refs/heads/gh-pages
          rm -rf *
          mv ../book/* .
          git add .
          git commit -m "Deploy $GITHUB_SHA to GitHub Pages"
          git push --force --set-upstream origin gh-pages